app/src/index.ts
app/src/nvim-events/on-content-change.ts
app/src/nvim-events/on-vim-leave-pre.ts
app/src/schemas.ts
app/src/server/websocket.ts
app/src/types.ts
app/src/utils.ts
app/src/web/explorer/footer.tsx
app/src/web/explorer/header.tsx
app/src/web/explorer/index.tsx
app/src/web/markdown/breadcrumbs.tsx
app/src/web/provider/context.ts
app/src/web/provider/provider.tsx
app/src/web/tailwind.css
lua/github-preview/init.lua

Allow users to start github-preview when not in a git repo

single file support

---

app/.prettierignore
app/src/web/markdown/breadcrumbs.tsx
app/src/web/tailwind.css

I don't know if this is the best solution, but we'll do this for now. Overflow is hidden.

fix(breadcrumbs): prevent breadcrumbs from wrapping on low width screens

---

app/github-preview.ts
app/index.ts
app/server/http.ts
lua/github-preview/init.lua
lua/github-preview/utils.lua

fix(goodbye): clear autocommands on unalive http

---

app/server/http.ts
app/types.ts
app/web/__main__.tsx
app/web/components/theme-provider.tsx
app/web/components/websocket-provider/provider.tsx
app/web/index.html
app/web/vite.config.ts

fix(themes): fix initial light theme flash

---

app/github-preview.ts

before getting file lines from filesystem, check if there's an open buffer that matches the path we're requesting and get the lines from there
fix #108

fix(get-entry): read entry from open buffer if exists

---

app/web/components/explorer/index.tsx
app/web/components/markdown/index.tsx
app/web/components/markdown/mermaid.ts

fix(mermaid): rerun on explorer expand & collapse

---

app/web/components/markdown/scroll.ts
docs/features.md

chore(todos): clear todos. we have github issues

---

README.md

only one setup example instead of one simple and one advanced

docs(readme): update installation docs

---

app/web/components/explorer/index.tsx
app/web/components/explorer/settings/collapsed-option.tsx
app/web/components/explorer/settings/collapsed.tsx
app/web/components/explorer/settings/index.tsx
app/web/components/filling-circle.tsx
app/web/static/tailwind.css

autoclose settings modal when modal was opened by a collapsed option
fix #161

fix(settings): autoclose settings modal

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml

udpate template to ask for plugin manager data
fix #176

ci(issue-templates): udpate bug issue template

---

docs/CODE_OF_CONDUCT.md

docs(code-of-conduct): add CODE_OF_CONDUCT.md

---

.github/PULL_REQUEST_TEMPLATE.md

docs: sample pull_request_template

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

update installation snippet to look more similar to lazy.nvim's
update readme example config to show log_level
fix #169

docs(packer): update packer.nvim installation

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Fox broken link to CONTRIBUTING.md which was previously called DEVELOPMENT.md

docs(readme): fix broken link

---

app/web/index.html

fix: update page name again

---

docs/CONTRIBUTING.md

update contributing docs with missing data, like commit format, prettier, eslint
fix #104

docs(contributing): add contributing docs

---

docs/CONTRIBUTING.md

docs(contributing): development before contributing

---

README.md

docs(readme): update title

---

app/web/components/icons/copy.tsx
app/web/components/markdown/breadcrumbs.tsx
app/web/static/tailwind.css

added button besides breadcrumbs to copy path
fix #203

feat: copy path

---

.github/PULL_REQUEST_TEMPLATE.md
.prettierrc.json
README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
package.json

update prettier config to format docs/ and update indentation from 4 -> 2 in Markdown files

docs(prettier): update prettier config

---

app/web/vite.config.ts

docs(comment): add comment

---

app/web/__main__.tsx
app/web/app.tsx

there's a warning from react/vite in the browser about a hot-reload error that happens when the entry file "__main__.tsx" hot reloads
fix #217

chore(vite): fix Vite warning during dev

---

README.md
app/web/components/explorer/index.tsx
app/web/components/markdown/index.tsx
app/web/components/markdown/mermaid.ts
app/web/components/markdown/post-process.ts
app/web/components/websocket-provider/context.ts
app/web/components/websocket-provider/provider.tsx
app/web/static/index.css
docs/FEATURES.md

This PR adds video rendering support. It works similar to github. Markdown must simply contain a URL
that points to a video and we render it.
fix #232

Video support

---

docs/FEATURES.md

A video demoing repository-mode
fix #131

docs(FEATURES.md): repository-mode video

---

docs/FEATURES.md

docs: fix typo

---

app/web/components/markdown/scroll.ts

docs: add comment

---

app/web/components/markdown/index.tsx
app/web/components/markdown/line-numbers.tsx
app/web/components/markdown/mermaid.ts
app/web/components/markdown/post-process.ts
app/web/components/markdown/scroll.ts
app/web/static/tailwind.css

the reason not to use window.url doesn't apply anymore

refactor: relative links slight refactor

---

docs/CONTRIBUTING.md

docs(CONTRIBUTING): add link to conventional commits

---

README.md
docs/CONTRIBUTING.md

If we want people to follow the rules, we should make it easier for them to find the relevant rules.

Add Table of contents to docs/CONTRIBUTING.md

---

docs/CONTRIBUTING.md

docs(contributing): add missing emoji to "development"
