wallpants/github-preview.nvim

- lua/github-preview/init.lua
if channel_id is not found, something went wrong. neovim can't use broadcast channel_id 0 to make an rpc request.
> fix: raise error if channel_id not found

- app/src/web/explorer/index.tsx
The only way for currentPath to be a dir is if the user is navigating with the mouse on the browser using the explorer or if the user clicked on a breadcrumb. We expand explorer to allow the user to continue navigating using the mouse.
> fix: expand explorer if currentPath is a dir

- app/src/web/markdown/cursor-line.tsx
- app/src/web/markdown/index.tsx
- app/src/web/markdown/scroll.ts
Fix offset calculation when first "line-start" attribute found is not 0.
> fix(scroll): fix scroll offset calculation

- README.md
- app/src/nvim-events/on-content-change.ts
- app/src/nvim-events/on-cursor-move.ts
there's no need to subscribe to events if "vim.rpcnotify" or "vim.rpcrequest" specify channel id
> refactor(nvim-events): remove explicit event subscription

- app/index.ts
- app/types.ts
- app/web/components/markdown/index.tsx
usually we trigger offset calculations on html element height change. sometimes we add new lines "\n" to the buffer, which doesn't increase the element height as markdown just eats the new lines and offsets become stale
re #110
> fix(cursorline): fix offsets being off when element height doesnt change

- app/web/components/markdown/index.tsx
disable scroll for one tick after updating a config, it's annoying having the thing scroll
fix #150
> fix(scroll): don't scroll on config update

- app/web/components/markdown/index.tsx
- app/web/components/markdown/post-process.ts
open external links in new tab to prevent the navigation stack from changing. autoclose only works if navigation stack is empty
fix #157
> fix(autoclose): open external links in new tab

- README.md
- docs/FEATURES.md
use relative links in markdown
we were using absolute links in case anyone ever visited `:h github-preview` but f that
> docs(readme): use relative links

- app/web/components/markdown/scroll.ts
Cursorline is commonly a bit off, but it is very off in fenced code. This PR fixes that. It's not perfectly centered, but I think good enough.
fix #208
> fix(scroll): adjust cursorline in fenced code

- app/web/components/markdown/mermaid.ts
I thought type detection was needed to pass the type as a param to render the diagram, but it turns out it's not actually needed.
> perf(mermaid): error handling & remove type detection

- app/web/components/markdown/mermaid.ts
Since mermaids were being memoized, they would not rerender after a theme change. We now reset memoized mermaids if theme changes to force a rerender.
> fix(mermaid): properly update mermaid colors on theme change

- docs/CONTRIBUTING.md
link was not pointing to latest file in main branch
fix #238
> docs(contributing): fix froken link to github-action

- lua/github-preview/functions.lua
Even if single-file mode was enabled, we were still trying to find a git repository root. In some cases, depending on the cwd of the user, the search could take a while and it would seem like the app froze. Now if the user explicitly enabled single-file mode, we don't even try searching for a repository root.
re #249
> fix(single-file): don't search for root if single-file mode is enabled

- lua/github-preview/utils.lua
There's no need to wrap `log_level` with quotes or brackets.
> refactor: refactor for consistency

- lua/github-preview/functions.lua
Add comment to document why we set the variable, it's not obvious.
> docs: add documenting comment

- lua/github-preview/functions.lua
- lua/github-preview/types.lua
type may collide with some other plugin's that uses the same name
> refactor(types): rename lua type to something more specific

- .github/workflows/release.yml
manually setup nodejs to fix semantic-release complaining about the included nodejs version
> ci(release): manually setup nodejs

- .github/workflows/release.yml
included version (16) is too low and some npm package complain
> ci(release): manually add nodejs to release github-action

- .github/dependabot.yml
> ci(dependabot): run dependabot checks "montly" instead of "weekly"

- lua/github-preview/functions.lua
remove flag when installing dependencies to avoid the plugin from crashing when the package.json dependencies in the repo have been updated but not the lockfile (this happens after dependabot updates)
> fix: remove "--frozen-lockfile" flag

- lua/github-preview/health.lua
This PR fixes two health check functions that are currently broken on Windows:
1. **Platform:** `vim.loop.os_uname().sysname` returns `"Windows_NT"` on Windows, so this was a nice, quick and easy fix.
2. **Commit Hash:** Now using a pure Lua method to get the plugin directory rather than relying on the shell. 
Before:
After:
SHA of fork:
I've also verified that this still works on Linux (Ubuntu on WSL):
> fix(healthcheck): platform and commit sha fixes for windows

- app/server/http.ts
Bun is throwing an error saying that 'headers' must be an object, which it already is. Removing the declaration seems to be fixing the error.
> fix(http-server): remove empty headers object
